backend:
  name: github
  repo: Tangara-Studio/Blog
  branch: main
  base_url: https://api.netlify.com # Para OAuth
  auth_endpoint: auth

# Usar develop branch en ambiente de desarrollo
local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Autor", name: "author", widget: "select", options: ["tangara-studio", "jwilschrey"], default: "tangara-studio", hint: "Para agregar más autores, edita src/data/authors.ts y este archivo" }
      - { label: "Fecha de Publicación", name: "pubDate", widget: "datetime" }
      - { label: "Imagen Destacada", name: "heroImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["devlog"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Idioma / Language", name: "language", widget: "select", options: ["en", "es"], default: "en", hint: "Selecciona el idioma del post / Select the post language" }
      - { label: "Contenido", name: "body", widget: "markdown" }
